@startuml
activate PinpointStarter
PinpointStarter -> PinpointStarter: start()
    PinpointStarter -> IdValidator: 1.getAgentId() ->  pinpoint.agentId \ngetApplicationName -> pinpoint.applicationName
    activate IdValidator
    IdValidator -->> PinpointStarter
    deactivate IdValidator

    PinpointStarter -> AgentDirBaseClassPathResolver: \t\t2.resolvePlugins() -> ${agentDir}/plugin/*.jar
    activate AgentDirBaseClassPathResolver
    AgentDirBaseClassPathResolver -->>  PinpointStarter
    deactivate AgentDirBaseClassPathResolver

    PinpointStarter -> DefaultTraceMetadataLoaderService: \t\t\t\t3.1.<<create>> -> Load Plugins meta by SPI: com.navercorp.pinpoint.common.trace.TraceMetadataProvider
    activate DefaultTraceMetadataLoaderService
    DefaultTraceMetadataLoaderService -->> PinpointStarter
    deactivate DefaultTraceMetadataLoaderService

    PinpointStarter -> DefaultServiceTypeRegistryService: \t\t\t\t\t\t3.2.<<create>> -> ServiceTypeRegistry
    activate DefaultServiceTypeRegistryService
    DefaultServiceTypeRegistryService -->> PinpointStarter
    deactivate DefaultServiceTypeRegistryService


    PinpointStarter -> DefaultAnnotationKeyRegistryService: \t\t\t\t\t\t\t\t3.3.<<create>> -> AnnotationKeyRegistry
    activate DefaultAnnotationKeyRegistryService
    DefaultAnnotationKeyRegistryService -->> PinpointStarter
    deactivate DefaultAnnotationKeyRegistryService

    PinpointStarter -> PinpointStarter: getConfigPath() => \n\t4.1.configPath: ${agentDir}/pinpoint.config
    PinpointStarter -> DefaultProfilerConfig: \t\t\t\t\t\t\t\t\t\t4.2.load(configPath)
    activate DefaultProfilerConfig
    DefaultProfilerConfig -->> PinpointStarter
    deactivate DefaultProfilerConfig


    PinpointStarter -> PinpointStarter: 5.1.resolveLib() => ${agentDir}/lib
    PinpointStarter -> AgentClassLoader: \t\t\t\t\t\t\t\t\t\t\t\t<<create>>
    activate AgentClassLoader
    AgentClassLoader -->> PinpointStarter
    deactivate AgentClassLoader

    PinpointStarter -> PinpointStarter: 5.2.getBootClass => DefaultAgent.class\ncreateAgentOption => DefaultAgentOption
    PinpointStarter -> AgentClassLoader: \t\t\t\t\t\t\t\t\t\t\t\t\t\t6.boot(option) => DefaultAgent   option->DefaultAgentOption
    activate AgentClassLoader
        AgentClassLoader -> DefaultAgent:  Constructor.newInstance(agentOption) \n<- ContextClassLoaderExecuteTemplate.execute|PinpointURLClassLoader
        activate DefaultAgent
        DefaultAgent -->> AgentClassLoader
        deactivate DefaultAgent
    AgentClassLoader -->> PinpointStarter: \t\t\t\t\t\t\t\t\t\t\t\t\t\tDefaultAgent
    deactivate AgentClassLoader

    PinpointStarter -> DefaultAgent: \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t7.start()
    activate DefaultAgent
    DefaultAgent -->> PinpointStarter
    deactivate DefaultAgent

PinpointStarter -> PinpointStarter: 8.registerShutdownHook(pinpointAgent)\n    pinpointAgent -> DefaultAgent
deactivate PinpointStarter
@enduml